version: '2'
services:
  elasticsearch:
    build:
      context: elastic/
    volumes: 
      - /root/elk-6.2.3/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /root/elk-6.2.3/elastic/logs/:/usr/share/elasticsearch/logs/
      - /root/elk-6.2.3/elastic/data/:/usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build:
      context: kibana/
    volumes:
      - /root/elk-6.2.3/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: logstash/
    volumes:
      - "/root/elk-6.2.3/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "/root/elk-6.2.3/logstash/data/:/usr/share/logstash/data/"
      - "/root/elk-6.2.3/logstash/pipeline/:/usr/share/logstash/pipeline/"
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch