version: '2'
services:
  elasticsearch:
    build:
      context: elastic/
    volumes: 
      - /root/elk-6.2.3/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build:
      context: kibana/
    volumes:
      - /root/elk-6.2.3/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: logstash/
    volumes:
      - "/root/elk-6.2.3/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch